Adjust java version block

diff --git a/scripts/java-version b/scripts/java-version
--- a/scripts/java-version
+++ b/scripts/java-version
@@ -13,10 +13,9 @@
 #===============================================================================
 
 set -o errexit  # Exit when a command fails
-                # Use || true if a command is allowed to fail
+# Use || true if a command is allowed to fail
 set -o nounset  # Treat unset variables as an error
 set -o pipefail # Exit when a command in a pipeline fails
 
-VERSION=$(java --version | head -1 | cut -d" " -f2)
-echo "${VERSION::2}"
+echo $(java -version 2>&1 | awk -F '"' '/version/ {print $2}')
 
